// Centralized Hong Kong Locations Dataset
// Single source of truth for primary (region), secondary (district), tertiary (area)

export interface LocationEntry {
  primary: string;
  secondary: string;
  tertiary?: string;
}

export const LOCATIONS: LocationEntry[] = [
  /* ----------------------- HONG KONG ISLAND ----------------------- */
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Kennedy Town" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Shek Tong Tsui" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Sai Ying Pun" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Sheung Wan" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Central" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Admiralty" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "Mid-Levels" },
  { primary: "Hong Kong Island", secondary: "Central and Western", tertiary: "The Peak" },

  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "Wan Chai" },
  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "Causeway Bay" },
  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "Happy Valley" },
  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "Tai Hang" },
  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "So Kon Po" },
  { primary: "Hong Kong Island", secondary: "Wan Chai", tertiary: "Jardine's Lookout" },

  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Tin Hau" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Braemar Hill" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "North Point" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Quarry Bay" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Sai Wan Ho" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Shau Kei Wan" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Chai Wan" },
  { primary: "Hong Kong Island", secondary: "Eastern", tertiary: "Siu Sai Wan" },

  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Pok Fu Lam" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Aberdeen" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Ap Lei Chau" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Wong Chuk Hang" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Shouson Hill" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Repulse Bay" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Chung Hom Kok" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Stanley" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Tai Tam" },
  { primary: "Hong Kong Island", secondary: "Southern", tertiary: "Shek O" },

  /* ----------------------------- KOWLOON ----------------------------- */
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Tsim Sha Tsui" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Tsim Sha Tsui East" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Yau Ma Tei" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Jordan (Kwun Chung)" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Mong Kok" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "Tai Kok Tsui" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "King's Park" },
  { primary: "Kowloon", secondary: "Yau Tsim Mong", tertiary: "West Kowloon" },

  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Mei Foo" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Lai Chi Kok" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Cheung Sha Wan" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Sham Shui Po" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Shek Kip Mei" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Yau Yat Tsuen" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Tai Wo Ping" },
  { primary: "Kowloon", secondary: "Sham Shui Po", tertiary: "Stonecutters Island" },

  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Hung Hom" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "To Kwa Wan" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Ma Tau Kok" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Ma Tau Wai" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Kai Tak" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Kowloon City" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Ho Man Tin" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Kowloon Tong" },
  { primary: "Kowloon", secondary: "Kowloon City", tertiary: "Beacon Hill" },

  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "San Po Kong" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Wong Tai Sin" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Tung Tau" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Wang Tau Hom" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Lok Fu" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Diamond Hill" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Tsz Wan Shan" },
  { primary: "Kowloon", secondary: "Wong Tai Sin", tertiary: "Ngau Chi Wan" },

  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Ping Shek" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Kowloon Bay" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Ngau Tau Kok" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Jordan Valley" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Kwun Tong" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Sau Mau Ping" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Lam Tin" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Yau Tong" },
  { primary: "Kowloon", secondary: "Kwun Tong", tertiary: "Lei Yue Mun" },

  /* -------------------------- NEW TERRITORIES -------------------------- */
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Sai Kung Town" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Tseung Kwan O" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Tiu Keng Leng" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Hang Hau" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Po Lam" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Clear Water Bay" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Pak Tam Chung" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "High Island" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "Sharp Island" },
  { primary: "New Territories", secondary: "Sai Kung", tertiary: "LOHAS Park" },

  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Sha Tin" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Tai Wai" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Ma On Shan" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Fo Tan" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Siu Lek Yuen" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Ma Liu Shui" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "City One" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Shek Mun" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Wu Kai Sha" },
  { primary: "New Territories", secondary: "Sha Tin", tertiary: "Che Kung Temple" },

  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tai Po Market" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tai Po Old Market" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tai Wo" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Lam Tsuen" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tai Po Kau" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tai Mei Tuk" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Ting Kok" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Plover Cove" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tap Mun (Grass Island)" },
  { primary: "New Territories", secondary: "Tai Po", tertiary: "Tung Ping Chau" },

  { primary: "New Territories", secondary: "North", tertiary: "Fanling" },
  { primary: "New Territories", secondary: "North", tertiary: "Sheung Shui" },
  { primary: "New Territories", secondary: "North", tertiary: "Sha Tau Kok" },
  { primary: "New Territories", secondary: "North", tertiary: "Ta Kwu Ling" },
  { primary: "New Territories", secondary: "North", tertiary: "Kwu Tung" },
  { primary: "New Territories", secondary: "North", tertiary: "Lo Wu" },
  { primary: "New Territories", secondary: "North", tertiary: "Sandy Ridge" },
  { primary: "New Territories", secondary: "North", tertiary: "Lung Yeuk Tau" },
  { primary: "New Territories", secondary: "North", tertiary: "Wu Kau Tang" },
  { primary: "New Territories", secondary: "North", tertiary: "Robin’s Nest" },

  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Tuen Mun Town Centre" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Siu Hong" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Sam Shing" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "So Kwun Wat" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Lung Kwu Tan" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Lam Tei" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Tai Lam Chung" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Butterfly" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Castle Peak" },
  { primary: "New Territories", secondary: "Tuen Mun", tertiary: "Hong Kong Gold Coast" },

  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Yuen Long Town" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Tin Shui Wai" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Ping Shan Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Ha Tsuen Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Kam Tin Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Pat Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "San Tin Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Shap Pat Heung" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Hung Shui Kiu" },
  { primary: "New Territories", secondary: "Yuen Long", tertiary: "Mai Po / Nam Sang Wai" },

  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Tsuen Wan" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Lei Muk Shue" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Ting Kau" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Sham Tseng" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Tsing Lung Tau" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Ma Wan" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Sunny Bay" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Nina Tower / Citywalk" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Belvedere" },
  { primary: "New Territories", secondary: "Tsuen Wan", tertiary: "Riviera" },

  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Kwai Chung" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Tsing Yi" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Lai King" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Kwai Fong" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Kwai Hing" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Cheung Ching" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Tsing Yi North" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Tsing Yi South" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Container Terminals" },
  { primary: "New Territories", secondary: "Kwai Tsing", tertiary: "Stonecutters Bridge Area" },

  /* --------------------------- ISLANDS DISTRICT --------------------------- */
  { primary: "Islands District", secondary: "Tung Chung" },
  { primary: "Islands District", secondary: "Chek Lap Kok (Hong Kong International Airport)" },
  { primary: "Islands District", secondary: "Discovery Bay" },
  { primary: "Islands District", secondary: "Mui Wo" },
  { primary: "Islands District", secondary: "Tai O" },
  { primary: "Islands District", secondary: "Cheung Chau" },
  { primary: "Islands District", secondary: "Lamma Island (Yung Shue Wan / Sok Kwu Wan)" },
  { primary: "Islands District", secondary: "Peng Chau" },
  { primary: "Islands District", secondary: "Ngong Ping" },
  { primary: "Islands District", secondary: "Po Toi" },
];
