-- ============================================================================
-- CHECKPOINT: pre-identity-migration
-- Date: 2026-07-04
-- Git tag: pre-identity-migration
--
-- Current state:
--   Users:        16 rows (real accounts to preserve)
--   Professionals: 3 rows (test data, ok to rebuild)
--   Projects:      0 rows
--
-- To rewind to this state:
--   1. git checkout pre-identity-migration
--   2. Run reverse SQL for any applied MANUAL_SQL steps in reverse order
--   3. Restore DB from backup if available
--
-- Steps in this migration series:
--   Step 1: MANUAL_SQL_ADD_IDENTITY_TABLE.sql              (forward)
--           MANUAL_SQL_REVERSE_IDENTITY_TABLE_STEP1.sql     (reverse)
--   Step 2: MANUAL_SQL_BACKFILL_IDENTITY_STEP2.sql          (forward)
--           MANUAL_SQL_REVERSE_IDENTITY_BACKFILL_STEP2.sql   (reverse)
--   Step 3: Prisma schema — Identity model added, prisma generate (code)
--   Step 4: Auth service — IdentityService, dual-read login (code)
--   Step 5: MANUAL_SQL_ADD_PERSONA_TABLE_STEP5.sql          (forward)
--           MANUAL_SQL_REVERSE_PERSONA_TABLE_STEP5.sql       (reverse)
--   Step 6a: MANUAL_SQL_FK_MIGRATION_STEP6A.sql             (forward — cross-cutting tables)
--           MANUAL_SQL_REVERSE_FK_MIGRATION_STEP6A.sql       (reverse)
--   Step 6b: MANUAL_SQL_FK_MIGRATION_STEP6B.sql             (forward — professional-only tables)
--           MANUAL_SQL_REVERSE_FK_MIGRATION_STEP6B.sql       (reverse)
-- ============================================================================
