"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { API_BASE_URL } from "@/config/api";
import { fetchWithRetry } from "@/lib/http";
import { useProfessionalAuth } from "@/context/professional-auth-context";
import { useNextStepModal } from "@/context/next-step-modal-context";
import { QRCodeSVG } from "qrcode.react";
import toast from "react-hot-toast";

// ── Types ────────────────────────────────────────────────────────
interface SiteAccessStatus {
  requestId: string | null;
  requestStatus: string;
  visitScheduledFor: string | null;
  visitScheduledAt: string | null;
  formattedVisitTime: string | null;
  hasAccess: boolean;
  siteInspectionAvailableOn?: string | null;
  bookedInspectionTimes?: string[];
  rescheduleRequired?: boolean | null;
  requiresReschedule?: boolean | null;
  visitDetails?: string | null;
  siteAccessData: {
    addressFull: string;
    unitNumber?: string;
    floorLevel?: string;
    buildingName?: string;
    district?: string;
    accessDetails?: string;
  } | null;
}

interface InspectSiteModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId?: string;
}

// ── Component ────────────────────────────────────────────────────
export function InspectSiteModal({ isOpen, onClose, projectId: projectIdProp }: InspectSiteModalProps) {
  const { accessToken } = useProfessionalAuth();
  const { state } = useNextStepModal();
  const projectId = projectIdProp || state.projectId || "";

  const mode = (() => {
    const key = state.actionKey || '';
    if (key === 'REQUEST_SITE_ACCESS') return 'book';
    if (key === 'REQUEST_SITE_RESCHEDULE') return 'reschedule-propose';
    return 'manage';
  })();

  const [status, setStatus] = useState<SiteAccessStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Booking form state
  const [selectedTime, setSelectedTime] = useState("");
  const [requestingSlot, setRequestingSlot] = useState(false);

  // Message to client
  const [messageText, setMessageText] = useState("");
  const [sendingMessage, setSendingMessage] = useState(false);

  // Visit notes + mark visited
  const [visitNotes, setVisitNotes] = useState("");
  const [markingVisited, setMarkingVisited] = useState(false);

  // QR check-in
  const [showQR, setShowQR] = useState(false);
  const [qrToken, setQrToken] = useState<string | null>(null);
  const [otpCode, setOtpCode] = useState<string | null>(null);
  const [generatingQr, setGeneratingQr] = useState(false);
  const [qrError, setQrError] = useState<string | null>(null);
  const [qrSecondsLeft, setQrSecondsLeft] = useState(0);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const confirmedToastShownRef = useRef(false);

  // ── Fetch site access status ───────────────────────────────────
  const fetchStatus = useCallback(async (silent = false) => {
    if (!isOpen || !projectId || !accessToken) return;
    if (!silent) {
      setLoading(true);
      setError(null);
    }
    try {
      const res = await fetchWithRetry(
        `${API_BASE_URL}/projects/${projectId}/site-access/status?_ts=${Date.now()}`,
        {
          method: "GET",
          cache: "no-store",
          headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
        },
      );
      if (!res.ok) throw new Error("Failed to load site access data");
      const data = await res.json();
      setStatus(data);
    } catch (err: any) {
      if (!silent) setError(err.message || "Failed to load");
    } finally {
      if (!silent) setLoading(false);
    }
  }, [isOpen, projectId, accessToken]);

  useEffect(() => { fetchStatus(); }, [fetchStatus]);

  // ── Send message to client ─────────────────────────────────────
  const handleSendMessage = async () => {
    const text = messageText.trim();
    if (!text) return;
    setSendingMessage(true);
    try {
      const res = await fetch(`${API_BASE_URL}/projects/${projectId}/chat/messages`, {
        method: "POST",
        headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ content: text }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.message || "Failed to send message");
      }
      toast.success("Message sent to client.");
      setMessageText("");
    } catch (err: any) {
      toast.error(err.message || "Failed to send message");
    } finally {
      setSendingMessage(false);
    }
  };

  // ── Mark as visited ────────────────────────────────────────────
  const handleMarkVisited = async () => {
    if (!status?.requestId) return;
    setMarkingVisited(true);
    try {
      const res = await fetch(
        `${API_BASE_URL}/projects/site-access-requests/${status.requestId}/confirm-visit`,
        {
          method: "PUT",
          headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({ visitDetails: visitNotes.trim() || undefined }),
        },
      );
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.message || "Failed to mark as visited");
      }
      toast.success("Site visit recorded.");
      confirmedToastShownRef.current = true;
      setQrToken(null);
      setShowQR(false);
      setQrSecondsLeft(0);
      void fetchStatus(true);
    } catch (err: any) {
      toast.error(err.message || "Failed to mark as visited");
    } finally {
      setMarkingVisited(false);
    }
  };

  // ── QR generation ──────────────────────────────────────────────
  const generateQr = async () => {
    if (generatingQr || !projectId || !accessToken) return;
    setGeneratingQr(true);
    setQrError(null);
    try {
      const res = await fetch(`${API_BASE_URL}/projects/${projectId}/site-start/generate`, {
        method: "POST",
        headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ purpose: "site_inspection" }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.message || "Failed to generate QR");
      }
      const { token, otp } = await res.json();
      setQrToken(token);
      setOtpCode(otp || null);
      setShowQR(true);
      setQrSecondsLeft(3 * 60); // 3 min
    } catch (err: any) {
      setQrError(err.message || "Failed to generate QR");
    } finally {
      setGeneratingQr(false);
    }
  };

  // QR countdown
  useEffect(() => {
    if (!qrToken || !showQR) return;
    const id = setInterval(() => {
      setQrSecondsLeft((prev) => {
        if (prev <= 1) { setQrToken(null); setShowQR(false); return 0; }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(id);
  }, [qrToken, showQR]);

  const address = status?.siteAccessData;

  // ── Auto-generate QR when address data loads ──
  useEffect(() => {
    const alreadyVisited = String(status?.requestStatus || '').toLowerCase() === 'visited';
    if (!isOpen || loading || error || !address || hasAutoGenerated || alreadyVisited) return;
    setHasAutoGenerated(true);
    generateQr();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, loading, error, address, hasAutoGenerated, status?.requestStatus]);

  // Reset QR state on close
  useEffect(() => {
    if (!isOpen) {
      setQrToken(null);
      setOtpCode(null);
      setShowQR(false);
      setQrSecondsLeft(0);
      setQrError(null);
      setHasAutoGenerated(false);
      confirmedToastShownRef.current = false;
    }
  }, [isOpen]);

  // Poll for client confirmation while the QR is active (3-min window).
  useEffect(() => {
    if (!isOpen || !showQR || !qrToken) return;
    const id = setInterval(() => { void fetchStatus(true); }, 3000);
    return () => clearInterval(id);
  }, [isOpen, showQR, qrToken, fetchStatus]);

  // Surface a one-time confirmation when the client completes the scan.
  useEffect(() => {
    if (!isOpen || !showQR) return;
    const visited = String(status?.requestStatus || '').toLowerCase() === 'visited';
    if (visited && !confirmedToastShownRef.current) {
      confirmedToastShownRef.current = true;
      toast.success('Client confirmed your check-in ✓');
      setQrToken(null);
      setShowQR(false);
      setQrSecondsLeft(0);
    }
  }, [isOpen, showQR, status?.requestStatus]);

  const formatCountdown = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m}:${String(s).padStart(2, "0")}`;
  };

  const INSPECTION_TIME_OPTIONS = Array.from({ length: 11 }, (_, i) => `${String(8 + i).padStart(2, "0")}:00`);

  const formatInspectionDate = (value?: string | null) => {
    if (!value) return '';
    // Parse as Hong Kong date (YYYY-MM-DD) to avoid UTC/local ambiguity
    const parts = value.split('-');
    if (parts.length === 3) {
      const d = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
      if (!Number.isNaN(d.getTime())) {
        return d.toLocaleDateString('en-HK', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
      }
    }
    return value;
  };

  const offeredDate = status?.siteInspectionAvailableOn || '';
  const bookedTimes = new Set(status?.bookedInspectionTimes || []);
  const reqStatus = (status?.requestStatus || 'none').toLowerCase();
  const needsReschedule = status?.rescheduleRequired === true || status?.requiresReschedule === true;
  const showBookingForm = mode === 'reschedule-propose' || !status?.requestId || needsReschedule;
  const canRequest = Boolean(offeredDate && selectedTime);

  const handleRequestSlot = async () => {
    if (!canRequest || !projectId || !accessToken) return;
    setRequestingSlot(true);
    try {
      const res = await fetch(`${API_BASE_URL}/projects/${projectId}/site-access/request`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ visitScheduledFor: offeredDate, visitScheduledAt: selectedTime }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.message || 'Failed to request slot');
      }
      toast.success(mode === 'reschedule-propose' ? 'New time proposed to the client' : 'Inspection slot requested');
      setSelectedTime('');
      state.onCompleted?.({ projectId, actionKey: state.actionKey });
      fetchStatus(); // refresh
    } catch (err: any) {
      toast.error(err.message || 'Failed to request slot');
    } finally {
      setRequestingSlot(false);
    }
  };

  const handleSkipVisit = async () => {
    if (!projectId || !accessToken) return;
    setRequestingSlot(true);
    try {
      const res = await fetch(`${API_BASE_URL}/projects/${projectId}/site-access/skip`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
      });
      if (!res.ok) throw new Error('Failed to skip site visit');
      toast.success('Site visit skipped. You can now submit your quote.');
      state.onCompleted?.({ projectId, actionKey: state.actionKey });
      onClose();
    } catch (err: any) {
      toast.error(err.message || 'Failed');
    } finally {
      setRequestingSlot(false);
    }
  };

  const visitLabel = status?.formattedVisitTime || null;
  const isVisited = reqStatus === 'visited';

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="w-full max-w-xl rounded-2xl border border-[#D4C8A0] bg-[#F5EEDE] shadow-2xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="shrink-0 flex items-center justify-between border-b border-[#D4C8A0] px-5 py-4">
          <h2 className="text-lg font-bold text-slate-900">
            {mode === 'book'
              ? 'Book a site inspection slot'
              : mode === 'reschedule-propose'
                ? 'Request a new inspection time'
                : state.modalContent?.title || 'Inspect site'}
          </h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 text-xl">&times;</button>
        </div>

        <div className="overflow-y-auto flex-1 px-5 py-4 space-y-4">
          {loading && (
            <div className="flex items-center justify-center py-8 text-slate-500 text-sm gap-2">
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-slate-300 border-t-slate-600" />
              Loading...
            </div>
          )}

          {error && (
            <div className="rounded-lg border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
          )}

          {!loading && !error && showBookingForm && (
            <div className="rounded-lg border border-[#D4C8A0] bg-white p-4 space-y-3">
              <h3 className="text-sm font-semibold text-slate-900">Select inspection slot</h3>
              <p className="text-xs text-slate-600">
                {offeredDate
                  ? 'Choose one available inspection slot on the client offered date. Times already selected by other professionals are disabled.'
                  : 'Client has not offered an inspection date yet.'}
              </p>
              {offeredDate ? (
                <>
                  <div>
                    <p className="mb-1 text-xs font-semibold text-slate-700">Inspection Date</p>
                    <div className="rounded-lg border border-[#D4C8A0] bg-[#F5EEDE] px-3 py-2 text-sm text-slate-900">
                      {formatInspectionDate(offeredDate)}
                    </div>
                  </div>
                  <div>
                    <p className="mb-2 text-xs font-semibold text-slate-700">Choose an hourly time</p>
                    <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
                      {INSPECTION_TIME_OPTIONS.map((timeOption) => {
                        const isBooked = bookedTimes.has(timeOption);
                        const isSelected = selectedTime === timeOption;
                        return (
                          <button
                            key={timeOption}
                            type="button"
                            onClick={() => setSelectedTime(timeOption)}
                            disabled={isBooked || requestingSlot}
                            className={`rounded-lg border px-3 py-2 text-sm font-semibold transition ${
                              isSelected
                                ? 'border-emerald-400 bg-emerald-50 text-emerald-700'
                                : isBooked
                                ? 'border-slate-200 bg-slate-100 text-slate-400 cursor-not-allowed'
                                : 'border-[#D4C8A0] bg-white text-slate-700 hover:border-[rgba(126,58,33,0.4)]'
                            }`}
                          >
                            {timeOption}
                          </button>
                        );
                      })}
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={handleRequestSlot}
                    disabled={requestingSlot || !canRequest}
                    className="w-full rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50 transition"
                  >
                    {requestingSlot
                      ? 'Requesting...'
                      : mode === 'reschedule-propose'
                        ? 'Propose new time'
                        : needsReschedule
                          ? 'Request Reschedule'
                          : 'Request Slot'}
                  </button>
                  {mode === 'book' && (
                    <button
                      type="button"
                      onClick={handleSkipVisit}
                      disabled={requestingSlot}
                      className="w-full rounded-lg border border-[#D4C8A0] px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-[#F5EEDE] disabled:opacity-50 transition"
                    >
                      Skip inspection
                    </button>
                  )}
                </>
              ) : (
                <p className="text-sm text-slate-500 italic">Waiting for client to offer a site inspection date.</p>
              )}
            </div>
          )}

          {!loading && !error && address && (
            <>
              {/* Date / visited status */}
              {isVisited ? (
                <p className="text-lg font-bold text-emerald-700">✅ Visit completed — {visitLabel}</p>
              ) : visitLabel ? (
                <p className="text-lg font-bold text-slate-800">{visitLabel}</p>
              ) : null}

              {/* Message — no label, just input + button */}
              <div className="flex gap-2">
                <input
                  type="text"
                  value={messageText}
                  onChange={(e) => setMessageText(e.target.value)}
                  onKeyDown={(e) => { if (e.key === "Enter") handleSendMessage(); }}
                  placeholder="Send message to client..."
                  className="flex-1 rounded-lg border border-[#D4C8A0] bg-white px-3 py-2 text-sm text-slate-800 focus:border-emerald-500 focus:outline-none"
                />
                <button
                  type="button"
                  onClick={handleSendMessage}
                  disabled={sendingMessage || !messageText.trim()}
                  className="shrink-0 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-40 transition"
                >
                  {sendingMessage ? "..." : "Send"}
                </button>
              </div>

              {/* Address — single line */}
              <div>
                <h3 className="text-sm font-semibold text-slate-700 mb-2">📍 Site Address</h3>
                <p className="rounded-lg border border-[#D4C8A0] bg-white p-3 text-sm text-slate-800">
                  {[
                    address.buildingName,
                    address.unitNumber,
                    address.floorLevel,
                    address.addressFull,
                    address.district,
                  ]
                    .filter(Boolean)
                    .join(', ')}
                </p>
              </div>

              {/* Google Maps Embed */}
              {process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY && (
                <div>
                  <div className="overflow-hidden rounded-lg border border-[#D4C8A0]">
                    <iframe
                      title="Site location"
                      width="100%"
                      height="200"
                      style={{ border: 0 }}
                      loading="lazy"
                      referrerPolicy="no-referrer-when-downgrade"
                      src={`https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&q=${encodeURIComponent(
                        [address.buildingName, address.unitNumber, address.addressFull, address.district, "Hong Kong"]
                          .filter(Boolean)
                          .join(", ")
                      )}`}
                    />
                  </div>
                </div>
              )}

              {/* Check-in — only show when not yet visited */}
              {!isVisited && (
              <>
              {!showQR ? (
                <button
                  type="button"
                  onClick={generateQr}
                  disabled={generatingQr}
                  className="w-full rounded-lg border border-[#D4C8A0] px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-[#F5EEDE] disabled:opacity-50 transition"
                >
                  {generatingQr ? "Generating..." : "QR Check-in"}
                </button>
              ) : (
                <div className="rounded-lg border border-[#D4C8A0] bg-white p-4 text-center space-y-3">
                  <div className="w-fit mx-auto rounded-xl bg-white p-2">
                    <QRCodeSVG value={qrToken || ""} size={220} />
                  </div>

                  {/* OTP code — client can type this instead of scanning */}
                  <div className="flex flex-col items-center gap-2">
                    <span className="text-xs text-slate-500">Or enter this code</span>
                    <div className="flex items-center gap-3">
                      <span className="text-2xl font-mono font-bold tracking-[0.3em] text-slate-800 select-all">
                        {otpCode || qrToken!.slice(0, 6)}
                      </span>
                      <button
                        type="button"
                        onClick={() => {
                          const code = otpCode || qrToken!.slice(0, 6);
                          navigator.clipboard.writeText(code).then(
                            () => toast.success('Code copied'),
                            () => toast.error('Failed to copy'),
                          );
                        }}
                        className="rounded-md border border-[#D4C8A0] px-2 py-1 text-xs font-semibold text-slate-700 hover:bg-[#F5EEDE] transition"
                      >
                        Copy
                      </button>
                    </div>
                  </div>

                  <div className="flex flex-col items-center gap-1">
                    <span className="text-xs text-slate-500">Expires in</span>
                    <span className={`text-lg font-mono font-bold tabular-nums ${qrSecondsLeft < 60 ? 'text-rose-500' : 'text-emerald-600'}`}>
                      {formatCountdown(qrSecondsLeft)}
                    </span>
                  </div>

                  {qrError && <p className="text-xs text-red-500">{qrError}</p>}
                </div>
              )}
              </>
              )}

              {/* Visit Notes — optional after visit, actionable before */}
              <div>
                <textarea
                  rows={3}
                  value={visitNotes}
                  onChange={(e) => setVisitNotes(e.target.value)}
                  placeholder={isVisited ? 'Add notes about the visit (optional)...' : 'Visit notes — measurements, materials, site conditions...'}
                  className="w-full rounded-lg border border-[#D4C8A0] bg-white px-3 py-2 text-sm text-slate-800 focus:border-emerald-500 focus:outline-none"
                />
              </div>

              {/* Mark as visited / Save notes */}
              {!isVisited ? (
              <button
                type="button"
                onClick={handleMarkVisited}
                disabled={markingVisited}
                className="w-full rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50 transition"
              >
                {markingVisited ? "Recording..." : "✅ Mark as Visited"}
              </button>
              ) : (
              <button
                type="button"
                onClick={handleMarkVisited}
                disabled={markingVisited || !visitNotes.trim()}
                className="w-full rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50 transition"
              >
                {markingVisited ? "Saving..." : "Save visit notes"}
              </button>
              )}
            </>
          )}

          {!loading && !error && !address && (
            <p className="text-sm text-slate-500 italic py-4">No address data available. The client may not have shared it yet.</p>
          )}
        </div>

        {/* Footer */}
        <div className="shrink-0 border-t border-[#D4C8A0] px-5 py-3">
          <button
            onClick={onClose}
            className="w-full rounded-lg bg-blue-600 py-2 text-sm font-medium text-white hover:bg-blue-700 transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
