'use client';

import { useEffect, useRef, useState, useCallback } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import toast from 'react-hot-toast';
import { API_BASE_URL } from '@/config/api';
import { useAuth } from '@/context/auth-context';
import { useProfessionalAuth } from '@/context/professional-auth-context';
import { useNextStepModal } from '@/context/next-step-modal-context';
import { WorkflowCompletionModal } from '@/components/workflow-completion-modal';
import { resolveNextStepModalContent } from '@/lib/next-step-modal-content';

interface StartOnSiteModalProps {
  isOpen: boolean;
  isLoading?: boolean;
  onClose: () => void;
}

const POLL_INTERVAL_MS = 5000; // check every 5 s whether the site is started
const QR_EXPIRY_MINUTES = 15;
const QR_GENERATE_TIMEOUT_MS = 15000;

export function StartOnSiteModal({ isOpen, onClose }: StartOnSiteModalProps) {
  const { state } = useNextStepModal();
  const { accessToken: clientAccessToken } = useAuth();
  const { accessToken: professionalAccessToken } = useProfessionalAuth();

  const isProfessional = (state.role || '').toUpperCase().includes('PROFESSIONAL');
  const accessToken = isProfessional ? professionalAccessToken : clientAccessToken;

  // ── Professional state ────────────────────────────────────────────────
  const [qrToken, setQrToken] = useState<string | null>(null);
  const [otpCode, setOtpCode] = useState<string | null>(null);
  const [secondsLeft, setSecondsLeft] = useState<number>(0);
  const [generatingQr, setGeneratingQr] = useState(false);
  const [qrError, setQrError] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // ── Client state ──────────────────────────────────────────────────────
  const scannerRef = useRef<any>(null);
  const scannerDivId = 'start-on-site-qr-scanner';
  const [scannerError, setScannerError] = useState<string | null>(null);
  const [confirming, setConfirming] = useState(false);
  const [manualOtpMode, setManualOtpMode] = useState(false);
  const [manualOtpCode, setManualOtpCode] = useState('');

  // ── Shared ────────────────────────────────────────────────────────────
  const [completionOpen, setCompletionOpen] = useState(false);
  const [showDetails, setShowDetails] = useState(false);
  const pollTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const modalContent = resolveNextStepModalContent(state.actionKey || '', state.modalContent);
  const hasDetails = Boolean(modalContent.detailsBody);

  // ── Generate QR (professional) ────────────────────────────────────────
  const generateQr = useCallback(async () => {
    if (!state.projectId) {
      setQrError('Project context is missing. Please close and reopen this step.');
      return;
    }
    if (!accessToken) {
      setQrError('Session not ready. Please wait a moment and try again.');
      return;
    }
    setGeneratingQr(true);
    setQrError(null);
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), QR_GENERATE_TIMEOUT_MS);
    try {
      const res = await fetch(
        `${API_BASE_URL}/projects/${state.projectId}/site-start/generate`,
        {
          method: 'POST',
          headers: { Authorization: `Bearer ${accessToken}` },
          signal: controller.signal,
        },
      );
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        const fallbackText = typeof err === 'string' ? err : '';
        throw new Error(err.message || fallbackText || `Failed to generate QR (${res.status})`);
      }
      const { token, otp, expiresAt } = await res.json();
      if (!token) {
        throw new Error('QR token was not returned by the server');
      }
      setQrToken(token);
      setOtpCode(otp || null);
      void expiresAt;
      setSecondsLeft(QR_EXPIRY_MINUTES * 60);
    } catch (e: any) {
      const isAbortError = e?.name === 'AbortError';
      const message = isAbortError
        ? 'QR generation timed out. Please try Regenerate.'
        : e.message || 'Could not generate QR code';
      setQrError(message);
      toast.error(message);
    } finally {
      clearTimeout(timeoutId);
      setGeneratingQr(false);
    }
  }, [state.projectId, accessToken]);

  // Professional UX: open directly to QR screen and generate token immediately.
  useEffect(() => {
    if (!isOpen || !isProfessional || !state.projectId || !accessToken) return;
    if (qrToken || generatingQr || hasAutoGenerated) return;
    setHasAutoGenerated(true);
    const rafId = window.requestAnimationFrame(() => {
      void generateQr();
    });
    return () => window.cancelAnimationFrame(rafId);
  }, [
    isOpen,
    isProfessional,
    state.projectId,
    accessToken,
    qrToken,
    generatingQr,
    hasAutoGenerated,
    generateQr,
  ]);

  // Countdown timer for QR expiry
  useEffect(() => {
    if (!qrToken || !isOpen) return;
    const id = setInterval(() => {
      setSecondsLeft((prev) => {
        if (prev <= 1) {
          setQrToken(null);
          setOtpCode(null);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(id);
  }, [qrToken, isOpen]);

  // ── Confirm site start (client, called after QR scan) ─────────────────
  const confirmSiteStart = useCallback(
    async (token: string) => {
      if (!state.projectId || !accessToken || confirming) return;
      setConfirming(true);
      try {
        const res = await fetch(
          `${API_BASE_URL}/projects/${state.projectId}/site-start/confirm`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${accessToken}`,
            },
            body: JSON.stringify({ token }),
          },
        );
        if (!res.ok) {
          const err = await res.json().catch(() => ({}));
          throw new Error(err.message || 'Confirmation failed');
        }
        setCompletionOpen(true);
      } catch (e: any) {
        toast.error(e.message || 'Could not confirm site start');
        setScannerError(e.message || 'Could not confirm site start');
      } finally {
        setConfirming(false);
      }
    },
    [state.projectId, accessToken, confirming],
  );

  const handleManualOtpSubmit = useCallback(() => {
    if (manualOtpCode.trim().length < 4) {
      toast.error('Please enter the full code');
      return;
    }
    confirmSiteStart(manualOtpCode.trim());
  }, [manualOtpCode, confirmSiteStart]);

  // ── QR Scanner lifecycle (client) ────────────────────────────────────
  useEffect(() => {
    if (!isOpen || isProfessional || manualOtpMode) return;

    let stopped = false;

    const startScanner = async () => {
      try {
        // html5-qrcode uses a class-based API; import it dynamically so it
        // only runs on the client (avoids SSR issues).
        const { Html5Qrcode } = await import('html5-qrcode');
        if (stopped) return;

        const scanner = new Html5Qrcode(scannerDivId);
        scannerRef.current = scanner;

        await scanner.start(
          { facingMode: 'environment' },
          { fps: 10, qrbox: { width: 250, height: 250 } },
          (decodedText: string) => {
            // Null the ref immediately so the cleanup effect doesn't double-stop
            scannerRef.current = null;
            scanner.stop().catch(() => {});
            confirmSiteStart(decodedText);
          },
          () => {
            // Scan failure — silently ignore per-frame misses
          },
        );
      } catch (err: any) {
        if (!stopped) {
          const msg =
            err?.message?.includes('Permission')
              ? 'Camera permission denied. Please allow camera access and try again.'
              : err?.message || 'Could not start camera.';
          setScannerError(msg);
        }
      }
    };

    startScanner();

    return () => {
      stopped = true;
      scannerRef.current
        ?.stop()
        .catch(() => {})
        .finally(() => {
          scannerRef.current = null;
        });
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, isProfessional, manualOtpMode]);

  // ── Poll for confirmation on professional side ────────────────────────
  // (so their modal updates if the client scans while it's open)
  useEffect(() => {
    if (!isOpen || !isProfessional || !state.projectId || !accessToken) return;

    const poll = async () => {
      try {
        const res = await fetch(
          `${API_BASE_URL}/projects/${state.projectId}`,
          { headers: { Authorization: `Bearer ${accessToken}` } },
        );
        if (!res.ok) return;
        const data = await res.json();
        if (data?.siteStartedAt) {
          setCompletionOpen(true);
        }
      } catch {
        // ignore
      }
    };

    pollTimerRef.current = setInterval(poll, POLL_INTERVAL_MS);
    return () => {
      if (pollTimerRef.current) clearInterval(pollTimerRef.current);
    };
  }, [isOpen, isProfessional, state.projectId, accessToken]);

  // Reset state when modal closes
  useEffect(() => {
    if (!isOpen) {
      setQrToken(null);
      setOtpCode(null);
      setSecondsLeft(0);
      setQrError(null);
      setHasAutoGenerated(false);
      setShowDetails(false);
      setScannerError(null);
      setConfirming(false);
      setManualOtpMode(false);
      setManualOtpCode('');
    }
  }, [isOpen]);

  const formatTime = (s: number) =>
    `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`;

  const modalTitle = modalContent.title || 'Start project on site';
  const modalBody =
    modalContent.body ||
    'Show this QR code to your client. They will scan it to confirm both parties are on site.';
  const modalImage = modalContent.imageUrl || '/assets/images/chatbot-avatar-icon.webp';

  if (!isOpen) return null;

  // ─── Completion state ─────────────────────────────────────────────────
  if (completionOpen) {
    return (
      <WorkflowCompletionModal
        isOpen={completionOpen}
        showConfetti
        completedLabel="Project started on site!"
        completedDescription={
          isProfessional
            ? 'The client has confirmed on-site presence. The project is now in progress.'
            : 'On-site start confirmed. Your project is now in progress!'
        }
        nextStep={null}
        onClose={() => {
          setCompletionOpen(false);
          state.onCompleted?.({ projectId: state.projectId, actionKey: state.actionKey });
          onClose();
        }}
      />
    );
  }

  // ─── Professional: show QR ────────────────────────────────────────────
  if (isProfessional) {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(81,55,32,0.35)] backdrop-blur-sm"
        onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
      >
        <div className="w-full max-w-md max-h-[80vh] mx-4 rounded-2xl border border-[rgba(120,53,15,0.18)] bg-[rgba(245,238,219,0.94)] shadow-2xl overflow-hidden">
          <div
            className="relative grid max-h-[80vh] [transform-style:preserve-3d] transition-transform duration-500 ease-out"
            style={{ transform: showDetails ? 'rotateY(180deg)' : 'rotateY(0deg)' }}
          >
            <div
              className="col-start-1 row-start-1 flex max-h-[80vh] flex-col overflow-hidden [backface-visibility:hidden]"
              aria-hidden={showDetails}
            >
              {hasDetails && (
                <button
                  type="button"
                  onClick={() => setShowDetails(true)}
                  className="absolute right-[1.625rem] top-4 z-20 h-8 w-8 rounded-full border border-[rgba(120,53,15,0.2)] bg-[rgba(245,238,219,0.9)] text-lg font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,1)]"
                  aria-label="Show details"
                >
                  i
                </button>
              )}

              <div className="next-step-scrollbar flex-1 overflow-y-auto px-6 pb-5 pt-10 text-center">
                <div className="flex flex-col items-center text-center">
                <div className="mb-4 flex items-center gap-4">
                  <img
                    src={modalImage}
                    alt="Step illustration"
                    className="h-12 w-12 rounded-full border border-[rgba(120,53,15,0.14)] object-cover flex-shrink-0"
                  />
                <h2 className="text-2xl font-bold text-[#FF7F50]">{modalTitle}</h2>
                </div>

                <div className="mt-6 flex flex-col items-center gap-4">
                  {qrError ? (
                    <div className="w-full rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 text-center">
                      {qrError}
                    </div>
                  ) : null}

                  {!qrToken && generatingQr ? (
                    <div className="flex flex-col items-center gap-3 py-6">
                      <div className="w-10 h-10 border-4 border-emerald-400 border-t-transparent rounded-full animate-spin" />
                      <p className="text-sm text-[rgba(126,58,33,0.55)]">Generating QR code...</p>
                    </div>
                  ) : !qrToken ? (
                    <div className="w-full rounded-xl border border-[rgba(120,53,15,0.14)] bg-[rgba(245,238,219,0.55)] px-4 py-5 text-sm text-[rgba(126,58,33,0.55)] text-center">
                      Tap <span className="font-semibold text-[#4A3623]">Regenerate</span> to generate a fresh QR code.
                    </div>
                  ) : (
                    <>
                      <div className="w-fit mx-auto rounded-xl bg-white p-3">
                        <QRCodeSVG value={qrToken!} size={220} />
                      </div>

                      {/* OTP code — client can type this instead of scanning */}
                      <div className="flex flex-col items-center gap-2">
                        <span className="text-xs text-[rgba(126,58,33,0.45)]">Or enter this code</span>
                        <div className="flex items-center gap-3">
                          <span className="text-2xl font-mono font-bold tracking-[0.3em] text-[#4A3623] select-all">
                            {otpCode || qrToken!.slice(0, 6)}
                          </span>
                          <button
                            type="button"
                            onClick={() => {
                              const code = otpCode || qrToken!.slice(0, 6);
                              navigator.clipboard.writeText(code).then(
                                () => toast.success('Code copied'),
                                () => toast.error('Failed to copy'),
                              );
                            }}
                            className="rounded-md border border-[rgba(120,53,15,0.2)] px-2 py-1 text-xs font-semibold text-[#4A3623] hover:bg-[rgba(245,238,219,0.8)] transition"
                          >
                            Copy
                          </button>
                        </div>
                      </div>

                      <div className="flex flex-col items-center gap-1">
                        <span className="text-xs text-[rgba(126,58,33,0.45)]">Expires in</span>
                        <span
                          className={`text-2xl font-mono font-bold tabular-nums ${
                            secondsLeft < 60 ? 'text-rose-400' : 'text-emerald-300'
                          }`}
                        >
                          {formatTime(secondsLeft)}
                        </span>
                      </div>

                      <p className="text-xs text-[rgba(126,58,33,0.45)] text-center">
                        Ask the client to open their &ldquo;Start project on site&rdquo; step and scan this code.
                      </p>
                    </>
                  )}
                </div>
              </div>
              </div>

              <div className="mt-auto flex items-center justify-end gap-3 border-t border-[rgba(120,53,15,0.14)] px-5 py-4">
                <button
                  onClick={generateQr}
                  disabled={generatingQr}
                  className="min-w-[110px] rounded-lg border border-[rgba(120,53,15,0.2)] px-4 py-2 text-base font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,0.9)] disabled:opacity-50"
                >
                  Regenerate
                </button>
                <button
                  onClick={onClose}
                  className="min-w-[110px] rounded-lg bg-emerald-600 px-4 py-2 text-base font-semibold text-white transition hover:bg-emerald-700"
                >
                  Close
                </button>
              </div>
            </div>

            <div
              className="col-start-1 row-start-1 flex max-h-[80vh] flex-col overflow-hidden [backface-visibility:hidden]"
              style={{ transform: 'rotateY(180deg)' }}
              aria-hidden={!showDetails}
            >
              <button
                type="button"
                onClick={() => setShowDetails(false)}
                className="absolute right-[1.625rem] top-4 z-20 h-8 w-8 rounded-full border border-[rgba(120,53,15,0.2)] bg-white text-lg font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,0.9)]"
                aria-label="Hide details"
              >
                ×
              </button>

              <div className="next-step-scrollbar flex-1 overflow-y-auto px-6 pb-6 pt-12 text-left">
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">More information</p>
                <h3 className="mt-3 text-2xl font-bold text-[#FF7F50]">{modalTitle}</h3>
                <p className="mt-5 text-sm leading-relaxed text-slate-600">
                  {modalContent.detailsBody || 'No additional details available for this step.'}
                </p>
              </div>

              <div className="mt-auto border-t border-[rgba(120,53,15,0.14)] px-5 py-4">
                <button
                  type="button"
                  onClick={() => setShowDetails(false)}
                  className="w-full rounded-lg border border-[rgba(120,53,15,0.2)] px-4 py-2 text-base font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,0.9)]"
                >
                  Back to action
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ─── Client: scan QR ─────────────────────────────────────────────────
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(81,55,32,0.35)] backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="w-full max-w-md max-h-[80vh] mx-4 rounded-2xl border border-[rgba(120,53,15,0.18)] bg-[rgba(245,238,219,0.94)] shadow-2xl overflow-hidden">
        <div
          className="relative grid max-h-[80vh] [transform-style:preserve-3d] transition-transform duration-500 ease-out"
          style={{ transform: showDetails ? 'rotateY(180deg)' : 'rotateY(0deg)' }}
        >
          {/* ── Front face ── */}
          <div
            className="col-start-1 row-start-1 flex max-h-[80vh] flex-col overflow-hidden [backface-visibility:hidden]"
            aria-hidden={showDetails}
          >
            {hasDetails && (
              <button
                type="button"
                onClick={() => setShowDetails(true)}
                className="absolute right-[1.625rem] top-4 z-20 h-8 w-8 rounded-full border border-[rgba(120,53,15,0.2)] bg-[rgba(245,238,219,0.9)] text-lg font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,1)]"
                aria-label="Show details"
              >
                i
              </button>
            )}

            <div className="next-step-scrollbar flex-1 overflow-y-auto px-6 pb-5 pt-10">
              <div className="flex flex-col items-center text-center">
                <div className="mb-4">
                  <img
                    src={modalImage}
                    alt="Step illustration"
                    className="h-20 w-20 rounded-full border border-[rgba(120,53,15,0.14)] object-cover"
                  />
                </div>

                <h2 className="text-2xl font-bold text-[#FF7F50]">{modalTitle}</h2>
                <p className="mt-3 text-base leading-relaxed text-stone-600">{modalBody}</p>

                <div className="mt-5 w-full">
                  {scannerError ? (
                    <div className="w-full rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 text-center">
                      {scannerError}
                    </div>
                  ) : confirming ? (
                    <div className="flex flex-col items-center gap-3 py-6">
                      <div className="w-10 h-10 border-4 border-emerald-400 border-t-transparent rounded-full animate-spin" />
                      <p className="text-sm text-[rgba(126,58,33,0.55)]">Confirming...</p>
                    </div>
                  ) : manualOtpMode ? (
                    <div className="flex flex-col items-center gap-3">
                      <input
                        type="text"
                        inputMode="numeric"
                        maxLength={10}
                        value={manualOtpCode}
                        onChange={(e) => setManualOtpCode(e.target.value.replace(/\D/g, ''))}
                        placeholder="Enter code from pro's screen"
                        autoFocus
                        className="w-full rounded-lg border border-[rgba(120,53,15,0.22)] bg-white/70 px-4 py-3 text-center text-xl font-mono tracking-[0.3em] text-[#4A3623] placeholder-[rgba(126,58,33,0.3)] outline-none focus:border-amber-500"
                      />
                      <button
                        type="button"
                        onClick={handleManualOtpSubmit}
                        disabled={manualOtpCode.trim().length < 4}
                        className="w-full rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50 transition"
                      >
                        Confirm start on site
                      </button>
                    </div>
                  ) : (
                    <div className="w-full rounded-xl overflow-hidden bg-black border border-[rgba(120,53,15,0.22)]" style={{ minHeight: 280 }}>
                      {/* html5-qrcode mounts its video into this div */}
                      <div id={scannerDivId} style={{ width: '100%' }} />
                    </div>
                  )}
                </div>

                {!scannerError && !confirming && (
                  <button
                    type="button"
                    onClick={() => { setManualOtpMode(!manualOtpMode); setScannerError(null); }}
                    className="mt-3 text-sm font-semibold text-[#FF7F50] hover:text-[#E67245] transition"
                  >
                    {manualOtpMode ? '← Scan QR code instead' : 'Enter code manually instead'}
                  </button>
                )}

                {!manualOtpMode && (
                <p className="mt-4 text-sm text-[rgba(126,58,33,0.55)]">
                  Point your camera at the QR code shown on the professional&apos;s screen.
                </p>
                )}

                <p className="mt-2 text-xs text-[rgba(126,58,33,0.45)]">
                  If camera access is blocked, allow permission and reopen this step.
                </p>
              </div>
            </div>

            <div className="mt-auto flex items-center justify-end gap-3 border-t border-[rgba(120,53,15,0.14)] px-5 py-4">
              <button
                onClick={onClose}
                disabled={confirming}
                className="min-w-[110px] rounded-lg bg-emerald-600 px-4 py-2 text-base font-semibold text-white transition hover:bg-emerald-700 disabled:opacity-50"
              >
                Close
              </button>
            </div>
          </div>

          {/* ── Back face (details) ── */}
          <div
            className="col-start-1 row-start-1 flex max-h-[80vh] flex-col overflow-hidden [backface-visibility:hidden]"
            style={{ transform: 'rotateY(180deg)' }}
            aria-hidden={!showDetails}
          >
            <button
              type="button"
              onClick={() => setShowDetails(false)}
              className="absolute right-[1.625rem] top-4 z-20 h-8 w-8 rounded-full border border-[rgba(120,53,15,0.2)] bg-white text-lg font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,0.9)]"
              aria-label="Hide details"
            >
              ×
            </button>

            <div className="next-step-scrollbar flex-1 overflow-y-auto px-6 pb-6 pt-12 text-left">
              <p className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-400">More information</p>
              <h3 className="mt-3 text-2xl font-bold text-[#FF7F50]">{modalTitle}</h3>
              <p className="mt-5 text-sm leading-relaxed text-slate-600">
                {modalContent.detailsBody || 'No additional details available for this step.'}
              </p>
            </div>

            <div className="mt-auto border-t border-[rgba(120,53,15,0.14)] px-5 py-4">
              <button
                type="button"
                onClick={() => setShowDetails(false)}
                className="w-full rounded-lg border border-[rgba(120,53,15,0.2)] px-4 py-2 text-base font-semibold text-[#4A3623] transition hover:bg-[rgba(245,238,219,0.9)]"
              >
                Back to action
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
